name=Adafruit seesaw Peripheral ATmega328
version=1.3.0
author=Adafruit
maintainer=Adafruit <info@adafruit.com>
sentence=Library for making seesaw i2c peripherals - ATmega328P/ATtiny support
paragraph=Library for making seesaw i2c peripherals in Arduino core. Supports ATmega328P, ATmega328PB, and ATtiny 0/1-series chips.
category=Sensors
url=https://github.com/adafruit/Adafruit_seesawPeripheral
architectures=avr,megaavr
depends=Adafruit seesaw Library
